# Generated by Django 4.1 on 2023-04-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeshyar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constvalue',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amuzeshyar.constvalue'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amuzeshyar.department'),
        ),
    ]
