# Generated by Django 4.1 on 2023-05-02 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeshyar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'شخص', 'verbose_name_plural': 'اشخاص'},
        ),
        migrations.AddField(
            model_name='major',
            name='bachelor_unit',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='تعداد واحد مورد نیاز برای کارشناسی'),
        ),
        migrations.AddField(
            model_name='major',
            name='master_unit',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='تعداد واحد مورد نیاز برای کارشناسی ارشد'),
        ),
        migrations.AddField(
            model_name='major',
            name='phd_unit',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='تعداد واحد مورد نیاز برای دکتری'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(verbose_name=' تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='father_name',
            field=models.CharField(max_length=50, verbose_name='نام بدر'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.BooleanField(default=0, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_id',
            field=models.CharField(db_column='national_id', db_index=True, max_length=10, primary_key=True, serialize=False, verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.constvalue', verbose_name='نقش سازمانی'),
        ),
    ]
