# Generated by Django 4.1 on 2023-05-07 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeshyar', '0002_alter_person_options_major_bachelor_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvoice',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.student'),
        ),
        migrations.AlterField(
            model_name='fixedtuitionfee',
            name='fee',
            field=models.IntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='fixedtuitionfee',
            name='field_of_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.major', verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='fixedtuitionfee',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.semester', verbose_name='ترم'),
        ),
        migrations.AlterField(
            model_name='fixedtuitionfee',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='سال'),
        ),
    ]
