# Generated by Django 4.1 on 2023-04-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeshyar', '0002_alter_constvalue_parent_alter_department_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='phone_number_type',
        ),
    ]
