# Generated by Django 4.1 on 2023-05-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeshyar', '0003_studentinvoice_student_alter_fixedtuitionfee_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.student'),
        ),
    ]
