# Generated by Django 4.1 on 2023-05-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amuzeshyar', '0004_studentpayment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='entry_year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.studentinvoice'),
        ),
    ]
