# Generated by Django 4.1 on 2023-05-28 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amuzeshyar', '0005_student_entry_year_alter_studentpayment_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'کلاس', 'verbose_name_plural': 'کلاسها'},
        ),
        migrations.AlterModelOptions(
            name='classschedule',
            options={'verbose_name': 'زمانبندی کلاس', 'verbose_name_plural': 'زمانهای کلاس'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'نیمسال آموزشی', 'verbose_name_plural': 'نیمسالهای آموزشی'},
        ),
        migrations.AddField(
            model_name='student',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='real_student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.announcementtext', verbose_name='اطلاعیه'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='create_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expiration_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='specific_degree_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.constvalue', verbose_name='مقطع'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='specific_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.department', verbose_name='دپارتمان'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='specific_entry_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.semester', verbose_name='نیمسال'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='specific_major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.major', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='specific_specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.specialization', verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='specific_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.student', verbose_name='دانش آموز'),
        ),
        migrations.AlterField(
            model_name='class',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='ظرفیت کلاس'),
        ),
        migrations.AlterField(
            model_name='class',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.course', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='class',
            name='exam_datetime',
            field=models.DateTimeField(verbose_name='تاریخ امتحان'),
        ),
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.professor', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.semester', verbose_name='نیمسال'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(verbose_name='روز هفته'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='end_at',
            field=models.TimeField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.room', verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.class', verbose_name='کلاس'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='start_at',
            field=models.TimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='classes_end_date',
            field=models.DateField(verbose_name='تاریخ اتمام کلاس'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='classes_start_date',
            field=models.DateField(verbose_name='تاریخ شروع کلاس'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='exams_end_date',
            field=models.DateField(verbose_name='تاریخ اتمام امتحانات'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='exams_start_date',
            field=models.DateField(verbose_name='تاریخ شروع امتحانات'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='registration_end_date',
            field=models.DateField(verbose_name='تاریخ پایان ثبت نام'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='registration_modification_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام حذف و اضافه'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='registration_modification_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع حذف و اضافه'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='registration_start_date',
            field=models.DateField(verbose_name='تاریخ شروع ثبت نام'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuzeshyar.constvalue', verbose_name='نوع نیمسال آموزشی'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='سال تحصیلی'),
        ),
    ]
